# in order to use 'trusty' dist, need this.
# see https://docs.travis-ci.com/user/trusty-ci-environment/
sudo: required

# trust dist provides a modern build chain (as opposed to 'precise' dist)
# which absolves us from having to install compilers and stuff
dist: trusty

language: node_js
node_js:
  - node # means use latest stable node version

notifications:
  slack: mpxcode:H8b77d0Vyoq3MGj5XMVQlBZQ